all: cache1D.c cache2Drows.c cache2Dcols.c cache2Dclash.c
	gcc cache1D.c -Wall -m32 -std=gnu99 -o cache1D
	gcc cache2Drows.c -Wall -m32 -std=gnu99 -o cache2Drows
	gcc cache2Dcols.c -Wall -m32 -std=gnu99 -o cache2Dcols
	gcc cache2Dclash.c -Wall -m32 -std=gnu99 -o cache2Dclash
